### PR TITLE
Include PUSP support relying on gridsite

### PR DESCRIPTION
**Pull request by enolfc**
Not for merging, just want to get some feedback on the feasibility of getting this or similar into the main repo.

This code relies on having gridsite available at Apache thus the GRST_* variables will be there. No changes are done to the validation of the proxy coming from user.

(now with better branch name)

### CODE REVIEW

**Comment by enolfc** [comment]
@alvarolopez any thoughts on this? Probably it should be triggered with a configuration variable

**Comment by enolfc** [comment]
Missing tests, though travis is failing :(

**Comment by alvarolopez** [comment]
@enolfc should I merge this change?

**Comment by enolfc** [comment]
now it should be ready for merge!

**Review by alvarolopez — APPROVED** [review]

**Pull request merged**
